# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site dockersettings
title: 法喜
email: allengaller (at) gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://allengaller.com" # the base hostname & protocol for your site
twitter_username: allengaller
github_username:  allengaller

# Build settings
markdown: kramdown
